import { useState } from 'react'

function App() {

  const [regionsN, setRegionN] = useState(0)
  const [world, setWorld] = useState("main")



  const regions = [

    {
      name1: "_Գլխավոր Էջ_",
      img1: "https://th.bing.com/th/id/OIP.xjzi5gBEt8ea9I-ISrG6hAHaEK?w=315&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img2: "https://th.bing.com/th/id/OIP.7GC3C8qY3g05htbOw8VV1wHaE8?w=233&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img3: "https://th.bing.com/th/id/OIP.1RWiCv4rEIRELlMUqSwglwAAAA?w=251&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img4: "https://media-cdn.tripadvisor.com/media/photo-s/0e/6a/30/e7/guest-house.jpg",
      img5: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/0Andranik_street_Hrazdan2.jpg/480px-0Andranik_street_Hrazdan2.jpg",
      img6: "https://th.bing.com/th/id/OIP.pHhA8Ztwcmr-nwn7_F9nVgHaE8?w=276&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img7: "https://th.bing.com/th/id/OIP.bGwqR484TanInyHv_QtMowHaE8?w=258&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img8: "https://th.bing.com/th/id/OIP.1p4MkBIDpRHdEBQyEUXzlAHaFj?w=240&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img9: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Yeghegnadzor_landscape3.jpg/480px-Yeghegnadzor_landscape3.jpg",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name2: "_Արագածոտն_",
      description: "Արագածոտնի մարզը իր մեջ նրառում նաև Փամբակի ու Ծաղկունյաց լեռնաշղթաների միջև ընկած տարածքը Այնտեղ մարդու կենսագործունեության, հատկապես տնտեսության վարման համար բավարար պայմաններ կան Եվ պատահական չէ, որ պատմության բոլոր ժամանակներում մարզի տարածքը միշտ իրեն է գրավել ոչ միայն ժողովրդի հոծ բազմություններ, այլեւ եղել է հայոց արքունական եւ ամառանոցային եւ որսորդական տարածք:Մարզն աչքի է ընկնում բնակլիմայական պայմանների բազմազանությամբ: Ըստ բարձրության տարեկան միջին ջերմաստիճանը և տեղումների քանակը խիստ տարբեր են։ Արագածի գագաթամերձ շրջանում տեղումները տարեկան հասնում են 850-900 մմ, իսկ համեմատաբար ցածրադիր (1000 մ ) բարձրություններում՝ 300 մմ։ Արարատյան դաշտին հարող հատվածներում ամռանը տաք է, իսկ ձմռանը` չափավոր ցուրտ: Ըստ բարձրության տարեկան միջին ջերմաստիճանը և տեղումների քանակը խիստ տարբեր են։ Արագածի գագաթամերձ շրջանում տեղումները տարեկան հասնում են 850-900 մմ, իսկ համեմատաբար ցածրադիր (1000 մ ) բարձրություններում՝ 300 մմ։ Արարատյան դաշտին հարող հատվածներում ամռանը տաք է, իսկ ձմռանը` չափավոր ցուրտ: Բնական լանդշաֆտային գոտիներից մարզում հանդիպում են կիսաանապատային, չոր լեռնատափաստանային, ալպյան և նիվալ գոտիները։ Տարածված են հատկապես շինանյութերը՝ տուֆը, բազալտը, կրաքարը, կավահողը, խարամը, պեմզան և պեռլիտը։ Վերջինս կազմում է նախկին Խորհրդային Միության ողջ պաշարի 90%-ը եւ իր որակական հատկություններով համարվում է աշխարհում լավագույններից մեկը: Մարզում են գտնվում նաեւ Ծաղկասար (2219 մ), Իրինդ (2050 մ), Արտենի (2047 մ) հանգած հրաբուխները։",
      img: "https://th.bing.com/th/id/OIP.h8hp4puMPTaQMAuy_CaC_QHaFs?w=200&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name4: "_Արարատ_",
      description: "Արարատի մարզի տարածքը եղել է պատմական Հայաստանի Այրարատ նահանգի Ոստան գավառի մի մասը, այն գավառի, որը միջնադարում հայտնի էր որպես մայրաքաղաքների գավառ: Այստեղ էին գտնվում Արտաշատ և Դվին մայրաքաղաքները: Արարատի մարզը սահմանակից է Թուրքիային և Ադրբեջանի կազմում գտնվող Նախիջևանի Ինքնավար Հանրապետությանը: Արարատի մարզի տարածքը որոշակիորեն բաժանվում է երկու մասի` հարթավայրային և լեռնային: Արարատյան դաշտի կլիման խիստ չորային է: Առանձնապես հաճելի է արևոտ, անհողմ, տևական աշունը, երբ հասունանում են այգիների ու դաշտերի բարիքները:Մարզի լեռնային մեծ մասը զբաղեցնում են Գեղամա լեռների լանջերը և Ուրծի ու Երանոսի լեռները: Այստեղ առանձին կղզյակներով պահպանվում է անտառը, որը հիմնել է հայոց Խոսրով Կոտակ թագավորը, IV դարում: Այդտեղ այժմ կազմակերպվել է Խոսրովի արգելոցը: Հայկական պետության վերելքների ու անկումների հետ մեկտեղ փոխվել են բնակչության թիվը և կազմը: Հայ բնակչությունը կրկին մեծամասնություն է կազմել 1830-ական թվականներից հետո, երբ տասնյակ հազարավոր հայեր Իրանի Սալմաստ և Խոյ գավառներից վերաբնակեցվեցին Արարատի մարզի ներկա տարածքում: Այժմ բնակչությունը միատարր է, բայց կան նաև ռուսներ, քրդեր ու ասորիներ, որոնք փոքր թիվ են կազմում: Տարածքի հարթավայրային` փոքր մասում են գտնվում գրեթե բոլոր բնակավայրերը: Մարզի լեռնային մասում բնակչությունը գրեթե բացակայում է: Միայն բարձրադիր գոտում, որն օգտագործվում է որպես ամառային արոտավայր, ամռան երեք-չորս ամիսներին հայտնվում է ժամանակավոր բնակչություն:",
      img: "https://th.bing.com/th/id/OIP.MeHcLrIGLMWjQ9N3QVclqQHaDt?w=326&h=175&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name5: "_Սյունիք_",
      description: "Ամենաբարձր լեռնագագաթը Կապուտջուղն  է /3904/: Հայտնի են նաև Բաղացսար, Խուստուփ, Մեծ Իշխանասար, Արամազդ, Ծղուկ լեռնագագաթները: Լեռնաշխարհի մարգագետինները, ճոխ արոտավայրերը հարմար են անասնապահության, իսկ գետահովիտները՝ երկրագործության զարգացման համար:Զգալի տարածք են ընդգրկում անտառները, որոնցից են Մթնաձորը, Սոսու բնական եզակի անտառը:Անտառներն հարուստ են եզակի բուսատեսակներով և կենդանիներով: Հայաստանի բնական հարստություններով աչքի ընկնող երկրամասերից է Սյունիքը: Հնագույն ժամանակներից այստեղ արդյունահանվել են պղինձ և այլ գունավոր մետաղներ: Երկրամասն ունի ջրառատ գետեր, որոնցից խոշոր են Որոտանն ու Ողջին:Անձավաջրի կիրճը գտնվում է Վայոց Ձորում՝ Ելփին գյուղի մոտակայքում։ Կիրճն առանձնահատուկ է իր անանցանելի թվացող նեղ ժայռերով և դեղնակարմրավուն երանգներով։Դեպի Անձավաջրի կիրճ արշավը հիմնականում ուղեկցվում է Խարանալեռի (1897 մ) արշավի հետ, որի գագաթից բացվում է տեսարան դեպի Գենուտ, Շրեշտասար, Քարկատար, Ձիասար և Ծակքար լեռնագագաթները։ Չքնաղի լեռները գտնվում են Լոռու մարզում։ Այդպես է կոչվում Բազումի լեռների կենտրոնական մասի մի հատվածը՝ Ծիրկաթին լեռից մինչև Հեղեղուտի լեռնանցքը։ Չքնաղ լեռը համանուն լեռնաշղթայի ամենաբարձր գագաթն է՝ 2837 մ։ Գագաթից բացվում է հիանալի տեսարան դեպի Փամբակի կիրճն ու Բազումի լեռները։ Իլկասար լեռը (1462 մ) գտնվում է Արարատի մարզում։ Այն շրջակայքի նկատմամբ լավ արտահայտված կոն է։ Տեղացիներն այն անվանում են նաև Օձասար։ Լեռան գագաթնամերձ հատվածում պահպանվում են հին ամրոցի մնացորդներ։",
      img: "https://th.bing.com/th/id/OIP.y4S8EmQ4jGOcj2Xx-MJUOwHaEJ?w=273&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7'",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name6: "_Արմավիր_",
      description: "Արմավիրի մարզը հարուստ է պատմական բացառիկ հուշարձաններով:Եզակի հուշարձան է Մեծամորի բլրի լանջին պեղված հինգհազարամյա հնության (բրոնզեդարյան) մետաղաձուլարանը:Պատմական մեծ արժեք են ներկայացնում ուրարտական քաղաք Արգիշտիխինիլիի ավերակները: Դրանց հարևանությամբ Արաքս գետի նախկին հունի ձախ ափին գտնվել է հայոց նախկին մայրաքաղաքը` Արմավիրը, որը դարեր շարունակ եղել է տնտեսական և մշակութային խոշոր կենտրոն ու մնացել է այդպիսին մինչև նոր մայրաքաղաքի` Արտաշատի հիմնադրումը:Դրանից քիչ արևմուտք` Արաքսի ու Ախուրյանի միախառնման տեղում նշմարվում են այլ նշանավոր քաղաքի` Երվանդունիների թագավորության վերջին մայրաքաղաքի` Երվանդաշատի փլատակները: Պատմաճարտարապետական մեծագույն արժեք է ներկայացնում նաև Սարդարապատի հուշահամալիրը: Արմավիրի մարզը բնակչության բացարձակ թվով գրավում է միջին տեղ, բայց առաջինն է բնակչության խտության ցուցանիշով: Բնակչության ավանդական զբաղմունքը գյուղատնտեսությունն է:Արմավիրի մարզկենտրոնն է Արմավիրը: Նախկինում Արմավիրը կոչվել է Սարդարապատ, ապա Հոկտեմբերյան: Մարզի աբողջ տարածքի նկատմամբ կենտրոնական դիրք ունի, գտնվում է Երևան-Վաղարշապատ-Արագած-Գյումրի կարևոր ավտոխճուղու վրա: Քաղաքում գործում են երկու տասնյակից ավելի արդյունաբերական ձեռնարկություններ, կրթամշակութային ու առողջապահական` մարզային նշանակության հիմնարկներ:Մարզում, ամբողջ երկրում և համայն հայության կյանքում իր բացառիկ նշանակությամբ առանձնանում է Վաղարշապատ (1945-1995թթ. կոչվել է Էջմիածին) քաղաքը: Բացառիկ է նրա հոգևոր մշակութային նշանակությունը:",
      img: "https://th.bing.com/th/id/OIP.r1DZfP3LlZf5LZstgUZQLwHaE6?w=268&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name7: "_Գեղարքունիք_",
      description: "ՀՀ Գեղարքունիքի մարզը գտնվում է ՀՀ տարածքի արևելքում: Մարզը սահմանակից է ՀՀ Տավուշի / հյուսիսում/, Կոտայքի և Արարատի /արևմուտքում/ և Վայոց Ձորի մարզերին /հարավում/, ինչպես նաև Ադրբեջանին /արևելքում/: Մարզի ամենաերկար  ձգվածությունը  հյուսիս-արևմուտքից հարավ-արևելք կազմում է 115 կմ, արևմուտքից արևելք` 85 կմ: Գեղարքունիքն  ամենախոշոր մարզն է ըստ  տարածքի և զբաղեցնում  է ՀՀ տարածքի 18%-ը: Մարզն  իր մեջ  ներառում  է 5 քաղաք` Գավառ, Ճամբարակ, Մարտունի, Սևան, Վարդենիս և 87 գյուղական  բնակավայրեր:  Բնակչության  խտությունը կազմում  է 44.5 մարդ/1ք.կմ: Մարզում բնակվում է 238.000.0 մարդ /01.01.2003թ./:  որոնց  մեծ մասը` 158.400.0-ը /66.5%/ գյուղական  բնակավայրերում: Բնակչության  թվաքանակում  տղամարդիկ կազմում են 48.2%, կանայք` 51.8%-ը: Գեղարքունիքի մարզի կլիման  բնորոշվում է երկարատև  և խստաշունչ ձմեռներով, քանի որ  գտնվում է  ընդհանուր առմամբ ծովի  մակերևույթից 2000-3500 մ բարձրության վրա: Մարզի ամենաբարձր կետը` Աժդահակ լեռան գագաթն է 3598մ: Բարձր լեռներ են Սպիտակասարը 3555 մ, Վարդենիսը 3522 մ, Գեղասարը 3446մ: Ամենաերկար  գետերն են Արգիճին (51 կմ), Գավառագետը (47 կմ), և Մասրիկը (45 կմ), առկա  են նաև  խառնարանային լճեր` Աժդահակ և Արմաղան /մինչև 50 մ տրամագծով և 15 մ խորությամբ/: Գեղարքունիքի մարզում  է  գտնվում  բարձր լեռնային , եզակի  էկոհամակարգով Սևանա լիճը, որի  ավազանի ընդհանուր մակերեսը կազմում  է շուրջ 5 հազ. քառ. կմ, լճի հայելու  մակերեսը` 1.2 հազ. քառ. կմ, ծավալը` 35.8 մլդ.խմ:",
      img: "https://image.freepik.com/free-photo/noratus-cemetery-sevan-lake-armenia_134785-1150.jpg",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name8: "_Կոտայք_",
      description: "Կոտայքի մարզ – գտնվում է Հայաստանի Հանրապետության կենտրոնական մասում, ծովի մակերեւույթից 900- 2500 մ բարձրության վրա: Տարածքն ընդգրկում է Հրազդան գետի վերին  և միջին ավազանն ու Մարմարիկ գետի ավազանն ամբողջությամբ: Հյուսիսից սահմանափակվում է Գութանասար, իսկ հյուսիս-արեւելքից` Հատիսի լեռնազանգվածներով: Հարավ-արևմուտքում աստիճանաբար ցածրանալով՝ ձուլվում է Արարատյան դաշտին: Կոտայքի սարավանդն ընկած է Հրազդան գետի միջին հոսանքի ձախափնյա մասից մինչև Գեղամա լեռների արևմտյան ստորոտը: Հրազդան գետի ձախակողմյան վտակների մի մասը գետնի տակ ներծծված ջրերի շնորհիվ գարնանը դուրս են ցայտում /շատ լինելու պատճառով դրանց անվանում են «40 աղբյուր»/:Կոտայքի մարզի ոռոգման համակարգում մեծ նշանակություն ունի Ակնա լիճը /3032մ. բարձրություն/, որով ջրարբիացվում են ամառային արոտավայրերը: Հիմնական լեռնագրական միավորներն են Կոտայքի և Եղվարդի բլրաալիքային սարավանդները, Մարմարիկի վտակներով կտրտված Փամբակի լեռնաշղթայի լանջերը, Գեղամա լեռնաշղթայի լեռնաճյուղերն ու լավային հոսքերը: Տիրապետող են կիսաանապատային, լեռնատափաստանային լանդշաֆտները` համապատասխան բուսական և կենդանական աշխարհներով: Կլիմայական գոտին խառն է, իսկ աշխարհագրական դիրքն, ընդհանուր առմամբ, նպաստավոր : Կոտայքի մարզի տարածքով են անցնում Երևան-Շորժա և Հրազդան-Իջևան երկաթուղիները, իսկ մարզկենտրոնից մինչեւ մայրաքաղաք ընդամենը 45 կմ է: Ազգաբնակչության 97,6 %- ը հայեր են: Ազգային փոքրամասնություններից մարզում բնակվում են` եզդիներ, ասորիներ, ռուսներ, քրդեր:",
      img: "https://th.bing.com/th/id/OIP.FyYALNsPRzlcLC-SEoh7-gHaFS?w=253&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7'",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name9: "_Լոռի_",
      description: "ՀՀ Լոռու մարզը տարածքի մեծությամբ ու բնակչության թվաքանակով երրորդն է հանրապետությունում (զբաղեցնում է ՀՀ տարածքի 12.7 %-ը): Գտնվում է հանրապետության հյուսիսում, սահմանակից է Վրաստանի Հանրապետությանը (110 կմ երկարությամբ), արեւմուտքից Շիրակի, արեւելքից Տավուշի, հարավից Կոտայքի եւ Արագածոտնի մարզերին: Սահմանամերձ բնակավայրերն են Արծնի, Ապավեն, Ձորամուտ, Պաղաղբյուր, Ջիլիզա: Մարզի տարածքով են անցնում Թբիլիսի-Երեւան երկաթուղու մի հատվածը: ՀՀ Լոռու մարզն ընդգրկում է Սպիտակի, Ստեփանավանի, Տաշիրի, Թումանյանի, Գուգարքի տարածաշրջանները, Վանաձոր, Սպիտակ, Ստեփանավան, Ալավերդի, Տաշիր, Ախթալա քաղաքները: Լոռու մարզում ծովի մակերեւույթից բարձրագույն կետը Աչքասար լեռան գագաթն է (3196մ), ամենացածրը՝ Դեբեդ գետի ստորին հոսանքի շրջանը (մոտ 380 մ):Լոռու մարզն ընդգրկում է Դեբեդ գետի ավազանը ամբողջությամբ եւ ունի լեռնային ռելիեֆ: Նրա տարածքում են ձգվում Ջավախքի, Բազումի, Փամբակի, Գուգարաց, Վիրահայոց, Հալաբի լեռնաշղթաները: Առանձնանում են Փամբակի, Լոռվա գոգավորությունները եւ Լոռվա ձորը: Մարզն աչքի է ընկնում համեմատաբար խոնավ կլիմայով: Միջին եւ բարձրադիր գոտում կլիման բարեխառն լեռնային է, տեւական, ցուրտ ձմեռներով: Ամեն տարի հաստատվում է կայուն ձնածածկույթ: Ամառները տաք են, համեմատաբար խոնավ: Տարեկան թափվում են 600-700 մմ մթնոլորտային տեղումներ: Նախալեռնային գոտում կլիման մերձարեւադարձային է, չափավոր շոգ եւ չորային ամառներով, մեղմ ձմեռներով: Ագրոկլիմայական տեսակետից ընկած է ինտենսիվ ոռոգման գոտում:",
      img: "https://th.bing.com/th/id/OIP.PUx6M4QmNKYi4IIIF84j3QHaFj?w=241&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name10: "_Շիրակ_",
      description: "Շիրակի մարզը գտնվում է ՀՀ հյուսիս-արևմուտքում: Մարզկենտրոնը՝ Գյումրի:  Մարզի տարածքում են գտնվում Արփի լիճ-ջրամբարը, Ախուրյանի ջրամբարի հայկական հատվածը, Մանթաշի ջրամբարը:  Շիրակի մարզի կենտրոնական և հարավային հատվածում տարածվում է Շիրակի դաշտը, իսկ հյուսիսային շրջանում՝ Աշոցքի սարահարթը: Շիրակի մարզում են տարածվում Փամբակի, Բազումի լեռնաշղթաների, Եղնախաղի, Ջավախքի, Արագածի լեռնազանգվածների մի մասը: Մարզը ռելիեֆի առումով կարելի է բաժանել երկու մասի: Հրաբխային, որն ընդգրկում է Ջավախք-Աշոցքի տարածաշրջանը, իր մեջ ընդգրկելով Ջավախքի և Եղնախաղի լեռնավահանները, Չլդրի լեռները և Աշոցքի սարավանդը։  Մյուս մասը կարելի է համարել ծալքաբեկորավոր, որն իր մեջ է ներառում Շիրակի ծալքաբեկորավոր լեռնաշղթան ու Շիրակի դաշտը։Մարզի տարածքով հոսող խոշոր գետը Ախուրյանն է, որի միայն վերին հոսքի շրջանն է անցնում բուն տարածքով, միջին հոսքի շրջանում այն սահմանային է։ Մարզի տարածքում են գտնվում Ախուրյանի համակարգին պատկանող Ցողամարգ, Իլլի, Կարկաչուն գետակները։ Մարզի միակ լիճը Արփին է:Շիրակում է գրանցվել ՀՀ բացարձակ նվազագույն ջերմաստիճանը՝ -46˚։",
      img: "https://th.bing.com/th/id/OIP.VJbFyK4w-OKT_Q3eYufcqwHaEt?w=256&h=189&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name11: "_Տավուշ_",
      description: "ՀՀ Տավուշի մարզը գտնվում է Հայաստանի Հանրապետության տարածքի հյուսիս-արևելյան հատվածում։ Մարզը հարավում սահմանակից է ՀՀ Գեղարքունիքի և Կոտայքի մարզերին, արևմուտքում՝ ՀՀ Լոռու մարզին, հյուսիսում` Վրաստանին և արևելքում՝ Ադրբեջանին։ Մարզն ունի մոտ 350 կմ միջպետական սահման, որից 300-ը Ադրբեջանի Հանրապետության հետ, 50-ը` Վրաստանի: Ծովի մակերևույթից ամենացածր կետը գտնվում է Դեբեդավան գյուղի մոտ՝ 380 մ, ամենաբարձր կետը Միափորի լեռնաշղթայի համանուն գագաթն է` 2993 մ: Մարզը գտնվում է ՀՀ չափավոր խոնավ տարածաշրջանում։ Արևափայլքի տարեկան տևողությունը 1900-2000 ժամ է։ Ամառները լինում են տաք, ձմեռները՝ մեղմ։ Գետերը պատկանում են Կասպից ծովի (Քուռ գետի) ավազանին և սնվում են հալոցքային, ստորերկրյա և անձրևային ջրերից: Մարզի բնությունը գեղատեսիլ է։ Ընդհանուր մակերեսի 51%-ը զբաղեցնում են խառը անտառները, որոնք աչքի են ընկնում բուսական և կենդանական աշխարհի բազմազանությամբ, բնական ժառանգության անզուգական հուշարձաններով։ Բնության նախաստեղծ վիճակի պահպանության, առավել հարստացման և տեղական պայմաններում նոր տեսակների ստացման նպատակով Աղստևի ավազանում ստեղծվել է Դիլիջանի ազգային պարկը և Իջևանի անտառային այգին` դենդրոպարկը։ Մարզի և հատկապես Աղստևի հովտի բնակլիմայական պայմանները (մեղմ կլիմա, թթվածնով հարուստ լեռնային մաքուր օդ, հանքային բուժիչ ջրեր, անտառներ, դեղաբույսերով հարուստ լեռնաշխարհ) չափազանց նպաստավոր են բնակչության հանգստի կազմակերպման, առողջության վերականգնման և միջազգային տուրիզմի ծավալման համար։",
      img: "https://www.armgeo.am/wp-content/uploads/2015/04/IMG_2549-450x300.jpg",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name12: "_Վայոց Ձոր_",
      description: "Վայոց ձորի մարզը ՀՀ մարզերի շարքում տարածքի մեծությամբ գրավում է միջին տեղ, իսկ բնակչության թվով ամենափոքր մարզն է։ Մարզը զբաղեցնում է 2308 քառ.կմ մակերես, հյուսիսից սահմանակից է Գեղարքունիքի մարզին, հյուսիսարևելքից` Արցախին, հարավարևելքից` Սյունիքին, հարավից` Նախիջևանի Հանրապետությանը (Ադրբեջան), արևմուտքից` Արարատի մարզին։ Վայոց ձորը բնակատեղի է եղել վաղնջական ժամանակներից։ Այս փաստի մասին վկայում են պեղումների ընթացքում հայտանաբերված նախամարդու իրերը, բրոնզե դարին վերաբեող դաշույնները, ճարմանդները, ապարանջանները, մատանիները և այլ իրեր։ Ժայռերին հայտնաբերվել են բազում փորագրություններ, որսորդական տեսարաններով և զանազան կենդանիներով։ Իսկ 2008 թվականին միջազգային հնագիտական արշավախմբի կողմից Վայոց ձորում կատարված նոր հայտնագործությունը ևս մեկ անգամ ապացուցեց, որ Վայոց ձորը եղել է բնակատեղի ավելի քան 5000 տարվա վաղեմությամբ։  Արշավախմբի կողմից Թռչունների քարայրում պեղումների արդյունքում հայտանաբերվել է 5500 տարվա հնության կաշվե կոշիկ` տրեխ։ Այն ամենահին կոշիկի նմուշն է, որ երբևէ գտնվել է ամբողջ աշխարհում և այժմ գտնվում է ՀՀ պատմության թանգարանում։ Քարանաձավում հայտնաբերվել են նաև ճզմած խաղողի մնացորդներ և գինու կարասների մի ամբողջ շարք (գինու արտադրամաս)։ Հնարավոր է, որ դա ամբողջ աշխարհում գինու արտադրության ամենահին ցիկլն է։ Մարզն ունի կտրտված մակերևույթ` լայն, խորը ձորերի և բարձր լեռների երկիր է։ Հարևան մարզերի հետ կապող ճանապարհները անցնում են բարձրադիր, դժվարամատչելի և ոլորապտույտ լեռնանցքներով։",
      img: "https://th.bing.com/th/id/OIP.YY9cEX4ZTNstuaQi_3f5RQHaCZ?w=337&h=113&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
    },
    {
      name13: "_English_",
      img11: "https://th.bing.com/th/id/OIP.Ms7ru2BOPiIuH6ykIe5kpQHaHb?w=162&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img12: "https://th.bing.com/th/id/OIP.Wf60m6fAGrNthfgL2VITigAAAA?pid=ImgDet&w=380&h=275&rs=1",
      description0: '__Aragatsotn__:Aragatsotn marz also includes the area between the Pambak and Tsaghkunyats mountain ranges. There are sufficient conditions for human life, especially the management of the economy. And it is no coincidence that in all times of history, the territory of the marz has always attracted not only large crowds of people, but also was an Armenian royal and summer house and hunting area. The region is notable for its variety of natural and climatic conditions. According to the altitude, the average annual temperature and amount of precipitation are very different. In the region near the summit of Aragats, annual precipitation reaches 850-900 mm, and in relatively low (1000 m) altitudes - 300 mm. In the areas adjacent to the Ararat Valley, it is hot in summer and moderately cold in winter. According to the altitude, the average annual temperature and amount of precipitation are very different. In the region near the summit of Aragats, annual precipitation reaches 850-900 mm, and in relatively low (1000 m) altitudes - 300 mm. In the areas adjacent to the Ararat Valley, it is hot in summer and moderately cold in winter. Among the natural landscape zones, semi-desert, dry mountain steppe, alpine and snow zones are found in the region. Especially common building materials are tuff, basalt, limestone, clay, slag, pumice and perlite. The latter makes up 90% of the entire stock of the former Soviet Union and is considered one of the best in the world due to its quality. The extinct volcanoes of Tsaghkasar (2219 m), Irind (2050 m), Arten (2047 m) are also located in the region. The water resources of the region are formed from the snow melt of Aragats mountain, rainfall and natural springs. The major rivers of the region are Kasagh and Geghadzor. There are many gutters. (Mastara culvert is notable). The Arzni-Shamiram canal passes through the territory of the region, and the Tallinn canal also operates. The region is notable for its abundance of reservoirs. Aparan, Halavar, Tsilkar, Nerkin Sasnashen, Davtashen, Talin, Verin Bazmaberd, Kakavadzor, Shenik, Ashnak, Sabunchi reservoirs are operating.',
      description1: "__Ararat__:The territory of Ararat Marz was a part of the Vostan Province of the historical Airarat Province of Armenia, the province known as the Province of Capitals in the Middle Ages. The capitals of Artashat and Dvin were located here. Ararat Marz borders Turkey and the Autonomous Republic of Nakhichevan, which is part of Azerbaijan. The territory of Ararat marz is somewhat divided into two parts: plain and mountain. The climate of the Ararat valley is very dry. The sunny, windless, long autumn is particularly pleasant, when the good things of the gardens and fields ripen. Most of the mountainous part of the region is occupied by the slopes of the Geghama Mountains and the Urtsi and Yeranos mountains. The forest founded by the Armenian king Khosrov Kotak in the 4th century is preserved here with separate islands. The Khosrov Reserve has now been organized there. Along with the ups and downs of the Armenian state, the number and composition of the population changed. The Armenian population became the majority again after the 1830s, when tens of thousands of Armenians from Iran's Salmast and Khoi provinces resettled in the present territory of Ararat Marz. Now the population is homogeneous, but there are also Russians, Kurds and Assyrians, who make up a small number. Almost all settlements are located in the lowland part of the territory. The population in the mountainous part of the region is almost non-existent. Only in the upland zone, which is used as summer pasture, does a temporary population appear for three to four months of summer. It is located on the Yerevan-Goris-Stepanakert highway, 10 km northwest of the historical Armenian capital Artashat, from which it got its name. Artashat is one of the medium-sized cities of the Republic of Armenia, which has a multi-branch industry. Over the last 3-4 decades, wine, fruit canning, terracotta, pottery factories have been built and are operating. Other cities of Ararat are Ararat, Masis and Vedi. Ararat is best known as the center of heavy industry. a cement plant and a gold mining plant are located here. Masis and Vedu are characterized by food and light industries. Masis is also a major railway freight station that has interregional importance and serves the city of Yerevan. The region has abundant rivers, the largest of which are Vorotan and Voghji.",
      description2: '__Syunik__:The highest peak is Kaputjugh /3904/. Baghatssar, Khustup, Mets Ishkhanasar, Aramazd, Tsghuk peaks are also known. The meadows and rich pastures of the highlands are suitable for cattle breeding, and the river valleys are suitable for the development of agriculture. A significant area is covered by forests, among which are Mtnadzor, the unique natural forest of Sosu. The forests are rich in unique plant species and animals. Syunik is one of the regions of Armenia with outstanding natural resources. Copper and other non-ferrous metals have been mined here since ancient times. The region has water-rich rivers, the largest of which are Vorotan and Voghji. Andzavajri gorge is located in Vayots Dzor, near the village of Yelpin. The gorge is special with its seemingly impassable narrow rocks and yellowish-red hues. The hike to Ansavajri gorge is mainly accompanied by the hike to Kharanaler (1897 m), from the top of which there is a view of Genut, Shrestasar, Karkatar, Dziasar and Tsakkar peaks. Chknagh mountains are located in Lori marz. This is the name of a part of the central part of the Bazum mountains, from Tsirkatin mountain to Heheghut pass. Mount Chknagh is the highest peak of the mountain range of the same name, 2837 m. From the top there is a wonderful view of Pambak gorge and Bazum mountains. Ilkasar mountain (1462 m) is located in Ararat region. It is a well-defined cone with respect to its surroundings. Locals also call it Odzasar. Remains of the old castle are preserved in the upper part of the mountain. And from the top there is a wonderful view of the Great and Little Massis, the Kotuts mountain and the Yeranos mountains. The ascent of Mount Ilkasar is especially beautiful in the winter months, when the air is cold and the views are clear. The ascent of Mount Ilkasar is often accompanied by a hike to the Valley of the Angels, which is unique with its narrow and red rocks.',
      description3: "__Armavir__:Armavir region is rich in unique historical monuments. A unique monument is the five-thousand-year-old (Bronze Age) smelter excavated on the slope of Metsamor hill. The ruins of the Urartian city of Argishtikhinili represent a great historical value. Next to them, on the left bank of the former channel of the Araks River, there is the former Armenian capital, Armavir, which was a major economic and cultural center for centuries and remained so until the new capital, Artashat, was founded. the ruins of Yervandashat, the last capital of the Yervanduni kingdom. The Sardarapat Memorial is also a great historical-architectural value. Armavir marz occupies an average place in absolute number of population, but it is the first in terms of population density. The traditional occupation of the population is agriculture. Armavir is the regional center of Armavir. Previously, Armavir was called Sardarapat, then Khotemberyan. It has a central position in relation to the entire territory of the region, it is located on the important highway Yerevan-Vagharshapat-Aragats-Gyumri. There are more than two dozen industrial enterprises, educational, cultural and health care institutions of regional importance operating in the city. The city of Vagharshapat (1945-1995 was called Etchmiadzin) stands out for its exceptional importance in the region, in the entire country and in the life of all Armenians. Its spiritual and cultural significance is exceptional. In that sense, Vagharshapat is not only a Pan-Armenian, but also a Pan-Armenian center. Due to the fact that the Saint Etchmiadzin Cathedral is located here.",
      description4: '__Gegharkunik__:Gegharkunik region of RA is located in the east of RA territory. The region borders the RA Tavush /north/, Kotayk and Ararat /west/ and Vayots Dzor marzes /south/, as well as Azerbaijan /east/. The longest stretch of the region is 115 km from northwest to southeast, 85 km from west to east. Gegharkunik is the largest marz by area and occupies 18% of the RA territory. The region includes 5 cities: Gavar, Chambarak, Martuni, Sevan, Vardenis and 87 rural settlements. The population density is 44.5 people/1 sq. km. 238,000 people live in the region /01.01.2003/. most of which - 158.400.0 /66.5%/ in rural areas. Men make up 48.2% of the population, women make up 51.8%. The climate of Gegharkunik marz is characterized by long and harsh winters, as it is generally located at an altitude of 2000-3500 m above sea level. The highest point of the region is the peak of Mount Azhdahak at 3598 m. High mountains are Spitakasar 3555 m, Vardenis 3522 m, Geghasar 3446 m. The longest rivers are Argichi (51 km), Gavaraget (47 km), and Masrik (45 km), there are also crater lakes - Azhdahak and Armaghan /up to 50 m in diameter and 15 m deep/. In Gegharkunik Marz, there is a high mountainous, unique ecosystem, Lake Sevan, the total area of which basin is about 5 thousand. sq. km, the mirror surface of the lake is 1.2 thousand. sq. km, volume: 35.8 billion cubic meters. It has special importance not only for the region, but also for the republic. Lake Sevan is the largest freshwater basin in the region. The lake has a significant impact not only on the environmental balance of the entire region, but also on the economy. The region of Gegharkunik is unique with its healthy climate, ancient lakeside monuments and centers of culture, features of the flora and fauna, and the beauty of the natural environment.',
      img13: "https://th.bing.com/th/id/OIP.h8hp4puMPTaQMAuy_CaC_QHaFs?w=200&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img10: "https://th.bing.com/th/id/OIP.MeHcLrIGLMWjQ9N3QVclqQHaDt?w=326&h=175&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img14: "https://th.bing.com/th/id/OIP.y4S8EmQ4jGOcj2Xx-MJUOwHaEJ?w=273&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img15: "https://th.bing.com/th/id/OIP.r1DZfP3LlZf5LZstgUZQLwHaE6?w=268&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      img16: "https://image.freepik.com/free-photo/noratus-cemetery-sevan-lake-armenia_134785-1150.jpg",
      img17: "https://siviaggia.it/wp-content/uploads/sites/2/2021/08/Erevan.jpg",
    },
  ]
  return (
    <div>
      <div style={{ border: "5px solid black", marginLeft: 1, marginTop: 1 }}>


        <div style={{ border: "2px solid black", backgroundColor: "black" }}>

          <div style={{ marginLeft: 380, display: "flex", color: "orange", width: 640, marginBottom: -80 }}>
            <p style={{ fontSize: 30 }}>ՀԱՅԱՍՏԱՆԻ ՀԱՆՐԱՊԵՏՈՒԹՅԱՆ ՄԱՐԶԵՐ</p></div>
          <img src={regions[regionsN].img12} style={{ width: 120, marginTop: -100, }}></img>
          <img src={regions[regionsN].img11} style={{ width: 100, marginLeft: 1200, marginTop: 45 }}></img>
          <div style={{ display: "flex", border: "1px solid white", marginTop: "-20px", width: 935, marginLeft: 250, color: "white", backgroundColor: "gray" }}>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name1}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name2}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name4}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name5}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name6}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name7}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name8}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name9}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name10}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name11}</div>)}</div>
            <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", backgroundColor: i === regionsN ? "orange" : null, }}>{x.name12}</div>)}</div>
          </div>
        </div>
        <div>{regions.map((x, i) => <div key={i} onClick={() => setRegionN(i)} style={{ border: "0px solid black", marginLeft: 1250, color: "white", marginTop: -25, width: 65, backgroundColor: i === regionsN ? "orange" : null, }}>{x.name13}</div>)}</div>


        <div style={{ marginTop: 15, marginLeft: 15, width: 750 }}>{regions[regionsN].description}</div><img src={regions[regionsN].img} style={{ width: 300, border: " 1px solid black", marginTop: -900, marginLeft: 800 }}></img>

        <div style={{ marginTop: "10px", display: "flex", }}>
          <img src={regions[regionsN].img2} style={{ width: 300, border: " 1px solid black", marginLeft: 110 }}></img>
          <img src={regions[regionsN].img3} style={{ width: 300, border: " 1px solid black", marginLeft: 10 }}></img>
          <img src={regions[regionsN].img4} style={{ width: 300, border: " 1px solid black", marginLeft: 10 }}></img>
          <img src={regions[regionsN].img5} style={{ width: 300, border: " 1px solid black", marginLeft: 10 }}></img>
        </div>
        <div style={{ marginTop: "10px", display: "flex" }}>
          <img src={regions[regionsN].img6} style={{ width: 300, border: " 1px solid black", marginLeft: 110 }}></img>
          <img src={regions[regionsN].img7} style={{ width: 300, border: " 1px solid black", marginLeft: 10 }}></img>
          <img src={regions[regionsN].img8} style={{ width: 300, border: " 1px solid black", marginLeft: 10 }}></img>
          <img src={regions[regionsN].img9} style={{ width: 300, border: " 1px solid black", marginLeft: 10 }}></img>
        </div>
        <img src={regions[regionsN].img13} style={{ width: 300, }}></img><div>{regions[regionsN].description1}</div>
        <img src={regions[regionsN].img10} style={{ width: 300, }}></img><div>{regions[regionsN].description2}</div>
        <img src={regions[regionsN].img14} style={{ width: 300, }}></img><div>{regions[regionsN].description3}</div>
        <img src={regions[regionsN].img15} style={{ width: 300, }}></img><div>{regions[regionsN].description4}</div>
        <img src={regions[regionsN].img16} style={{ width: 300, }}></img>
      </div></div>
  )
}
export default App